title: Building a Hawk 289
author: R Hattersley
email: rhattersley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Documenting the process of building a Hawk 289 from an old MGB.

theme: minima

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: rhattersley # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
